Repository wecode-bootcamp-korea/17-2nd-CLASS404-backend, pull requests merged in 2021-03, with the labels that each got.

#1 [17기 이동근] Class404 models.py 작성완료
  \
  class404/settings.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: Rebase 요청

#3 [17기 박재현] 카카오톡 회원가입/로그인 뷰 작성
  class404/urls.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#7 [17기 김치오] productlist View 작성
  class404/urls.py
  order/migrations/0001_initial.py
  product/tests.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  user/utils.py
Labels: Status: Accepted

#8 [17기 김치오]ProductdetailView작성 및 유닛테스트 완료.
  product/tests.py
  product/urls.py
  product/views.py
  user/utils.py
Labels: Status: Accepted

#9 [17기 박재현] 마이페이지 작성
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#4 [17기 이준하]ADD : signup view 작성, test.py 작성
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#6 [17기 이준하] signin 작성완료, utils.py 작성완료, test.py 작성완료
  product/migrations/0001_initial.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#10 [17기 박재현] 마이페이지 로직 및 unit test 수정
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#11 [17기 김치오] class404/utils.py 작성
  class404/settings.py
  class404/utils.py
  product/tests.py
  product/urls.py
  product/views.py
  user/urls.py
Labels: Status: 리뷰 요청

#13 [17기 박재현] product like view 추가, 불필요한 파일 삭제
  aws_s3.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  utils.py
Labels: Status: Accepted

#12 [17기 박재현] 마이페이지 유저 프로필 이미지 수정 기능 구현
  class404/settings.py
  class404/utils.py
  product/tests.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#14 [17기 박재현] 일반 / 카카오톡 로그인 프로필 이미지 전달
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청
